/**
 * Shared math helpers that re-derive pf1's own class-level formulas
 * (module/models/item/class-model.mjs in the pf1 source) at an arbitrary
 * level, so the house rules can compute "what this class's base save/BAB
 * would be at a different level" without touching pf1 source.
 *
 * IMPORTANT: these intentionally mirror
 * RefCode/module/models/item/class-model.mjs:300-357 exactly (same config
 * tables, same rollData shape) so the recomputed value is *directly*
 * comparable to the class item's own already-computed
 * `system.savingThrows[id].base` / `system.babBase` — see
 * changes/saves-bab-lag.mjs for how the diff is used.
 */

/**
 * Recompute what a class item's base save bonus would be at an arbitrary
 * level (instead of its own current level), using the same formula table
 * pf1 itself used to compute `classItem.system.savingThrows[saveId].base`.
 *
 * Returns `null` if the class uses a "custom" save formula for this save,
 * since a custom formula is the item author's own responsibility and pf1
 * doesn't publish a reusable table for it — callers should treat `null` as
 * "no lag adjustment possible, leave the core-computed value as-is."
 *
 * @param {pf1.documents.ItemPF} classItem
 * @param {"fort"|"ref"|"will"} saveId
 * @param {number} level - Level to evaluate the table at (e.g. a lagged level).
 * @returns {number|null}
 */
export function recomputeClassSaveAtLevel(classItem, saveId, level) {
  // CORRECTION (verified live): `pf1.settings` doesn't exist in the
  // installed v11.11 build (another RefCode-vs-shipped-build drift, same
  // family as module.mjs's hook-name corrections) — the actual world
  // setting id is read via the standard Foundry settings API instead.
  const useFractional = game.settings.get("pf1", "useFractionalBaseBonuses");
  const saveFormulas = useFractional
    ? pf1.config.classFractionalSavingThrowFormulas
    : pf1.config.classSavingThrowFormulas;

  const classType = classItem.system.subType || "base";
  const saveData = classItem.system.savingThrows?.[saveId];
  const saveType = saveData?.value;
  if (!saveType || saveType === "custom") return null;

  const formula = saveFormulas?.[classType]?.[saveType];
  if (formula == null) return 0;

  // pf1's own class-model computation uses hitDice === level for classes
  // without an alternate HD progression (the normal case for every class
  // eligible to be a Secondary class per isEligibleSecondary()).
  return pf1.dice.RollPF.safeRollSync(formula, { level, hitDice: level }).total;
}

/**
 * The delta to push as an additive Change so that the TOTAL base save
 * contributed by the Primary+Secondary pair ends up equal to
 * `max(primary.base, secondary.base @ laggedLevel)`, per Docs/house-rules
 * §3.1 — NOT their sum.
 *
 * pf1's own multiclass aggregation *sums* every class's base save
 * (`base-character-model.mjs:1690-1745` pushes one additive Change per
 * class), so by the time this fires, pf1 has already contributed
 * `primary.base + secondary.base` (both at their real, lockstep level).
 * Since `pf1.change.defaults` can only add Changes, not remove pf1's own,
 * the delta needed is:
 *
 *   desired = max(primary.base, secondary.base @ laggedLevel)
 *   core    = primary.base + secondary.base   (both at real level)
 *   delta   = desired - core
 *
 * which correctly cancels the sum down to the max regardless of which side
 * is larger.
 *
 * @param {pf1.documents.ItemPF} primary
 * @param {pf1.documents.ItemPF} secondary
 * @param {"fort"|"ref"|"will"} saveId
 * @param {number} laggedLevel - Secondary's lagged level (see class-roles.mjs).
 */
export function maxSaveDelta(primary, secondary, saveId, laggedLevel) {
  const primaryBase = primary.system.savingThrows?.[saveId]?.base ?? 0;
  const secondaryBase = secondary.system.savingThrows?.[saveId]?.base ?? 0;
  const secondaryLagged = recomputeClassSaveAtLevel(secondary, saveId, laggedLevel) ?? secondaryBase;

  const desired = Math.max(primaryBase, secondaryLagged);
  const core = primaryBase + secondaryBase;
  return desired - core;
}

/* -------------------------------------------- */
/* Skill-point pools (§2.2)                      */
/* -------------------------------------------- */

/** The six abilities that each generate an attribute-restricted skill-point pool. */
export const POOL_ABILITIES = /** @type {const} */ (["str", "dex", "con", "int", "wis", "cha"]);

/** Flat, always-generic skill points granted per level regardless of ability scores. */
export const FLAT_SKILL_POINTS_PER_LEVEL = 2;

/**
 * Points generated by one ability's pool: its modifier, floored at 0 (a
 * negative modifier contributes 0 points, never a deduction) — see
 * Docs/house-rules Open Question #7 (resolved).
 *
 * @param {pf1.documents.ActorPF} actor
 * @param {"str"|"dex"|"con"|"int"|"wis"|"cha"} abilityId
 */
export function abilityPoolPoints(actor, abilityId) {
  const mod = actor.system.abilities?.[abilityId]?.mod ?? 0;
  return Math.max(mod, 0);
}

/**
 * All 7 pools for a level of this actor: one per ability plus the flat
 * generic bonus. Only the "con" pool is unrestricted-by-default per §2.2.2
 * (spendable on any skill); the other five are restricted to skills
 * governed by that ability (with Intimidate special-cased to allow either
 * "str" or "cha" — see ui/skill-pool-panel.mjs, which is where that
 * restriction is actually enforced/displayed).
 *
 * @param {pf1.documents.ActorPF} actor
 * @returns {Record<string, number>}
 */
export function skillPointPools(actor) {
  const pools = {};
  for (const id of POOL_ABILITIES) pools[id] = abilityPoolPoints(actor, id);
  pools.flat = FLAT_SKILL_POINTS_PER_LEVEL;
  return pools;
}

/** Sum of all 7 pools — the total skill points granted this level. */
export function totalSkillPointsPerLevel(actor) {
  return Object.values(skillPointPools(actor)).reduce((sum, v) => sum + v, 0);
}

/**
 * pf1's own skill id for Intimidate is literally `"int"` — a different
 * namespace than (and easy to confuse with) the Intelligence ABILITY id
 * `"int"`. `pf1.config.skills.int.ability` is `"cha"` by default; this
 * constant exists so every reference to "the Intimidate skill id" in this
 * module goes through one clearly-labeled name instead of a bare `"int"`
 * that reads like the ability.
 */
export const INTIMIDATE_SKILL_ID = "int";

/**
 * Which skill-point pools a given skill's ranks may be paid from: its own
 * governing ability's pool, plus the always-unrestricted "con" and "flat"
 * pools — with Intimidate additionally allowed to draw from "str" per
 * Docs/house-rules §2.2 ("Intimidate may use either STR or CHA").
 *
 * @param {string} skillId
 * @returns {string[]} pool keys (a subset of [...POOL_ABILITIES, "flat"])
 */
export function skillGoverningPools(skillId) {
  const ability = pf1.config.skills?.[skillId]?.ability;
  const pools = new Set(["con", "flat"]);
  if (ability) pools.add(ability);
  if (skillId === INTIMIDATE_SKILL_ID) pools.add("str");
  return [...pools];
}
