/**
 * Shared math helpers that re-derive pf1's own class-level formulas
 * (module/models/item/class-model.mjs in the pf1 source) at an arbitrary
 * level, so the house rules can compute "what this class's base save
 * would be at a different level" without touching pf1 source.
 *
 * IMPORTANT: these intentionally mirror
 * RefCode/module/models/item/class-model.mjs:300-357 exactly (same config
 * tables, same rollData shape) so the recomputed value is *directly*
 * comparable to the class item's own already-computed
 * `system.savingThrows[id].base` — see changes/saves-bab-lag.mjs for how
 * Primary vs lagged-Secondary bases are compared. Secondary BAB is not
 * recomputed here: it is zeroed at the source
 * (`registerSecondaryBabSuppression`).
 */

/**
 * Recompute what a class item's base save bonus would be at an arbitrary
 * level (instead of its own current level), using the same formula table
 * pf1 itself used to compute `classItem.system.savingThrows[saveId].base`.
 *
 * Returns `null` if the class has no save type for this save (callers
 * should then leave the stored base as-is). Custom formulas are evaluated
 * at `level` the same way pf1 evaluates them at the class's own level.
 *
 * @param {pf1.documents.ItemPF} classItem
 * @param {"fort"|"ref"|"will"} saveId
 * @param {number} level - Level to evaluate the table at (e.g. a lagged level).
 * @returns {number|null}
 */
export function recomputeClassSaveAtLevel(classItem, saveId, level) {
  // CORRECTION (verified live): `pf1.settings` doesn't exist in the
  // installed v11.11 build (another RefCode-vs-shipped-build drift, same
  // family as module.mjs's hook-name corrections) — the actual world
  // setting id is read via the standard Foundry settings API instead.
  const useFractional = game.settings.get("pf1", "useFractionalBaseBonuses");
  const saveFormulas = useFractional
    ? pf1.config.classFractionalSavingThrowFormulas
    : pf1.config.classSavingThrowFormulas;

  const classType = classItem.system.subType || "base";
  const saveData = classItem.system.savingThrows?.[saveId];
  const saveType = saveData?.value;
  if (!saveType) return null;

  let formula;
  if (saveType === "custom") {
    formula = saveData.custom || "0";
  } else {
    formula = saveFormulas?.[classType]?.[saveType];
    if (formula == null) return 0;
  }

  // pf1's own class-model computation uses hitDice === level for classes
  // without an alternate HD progression (the normal case for every class
  // eligible to be a Secondary class per isEligibleSecondary()).
  return pf1.dice.RollPF.safeRollSync(formula, { level, hitDice: level }).total;
}

/**
 * Compare Primary's already-computed base save against Secondary's table
 * at the lagged level. Highest wins; Primary wins a tie. Used by
 * `changes/saves-bab-lag.mjs` to keep only that class's contribution
 * instead of summing both and cancelling.
 *
 * @param {pf1.documents.ItemPF} primary
 * @param {pf1.documents.ItemPF} secondary
 * @param {"fort"|"ref"|"will"} saveId
 * @param {number} laggedLevel - Secondary's lagged level (see class-roles.mjs).
 * @returns {{ primaryBase: number, secondaryLagged: number, winner: "primary"|"secondary", value: number }}
 */
export function compareDualClassSave(primary, secondary, saveId, laggedLevel) {
  const primaryBase = Number(primary.system.savingThrows?.[saveId]?.base) || 0;
  const secondaryStored = Number(secondary.system.savingThrows?.[saveId]?.base) || 0;
  const secondaryLagged = recomputeClassSaveAtLevel(secondary, saveId, laggedLevel) ?? secondaryStored;
  const secondaryWins = secondaryLagged > primaryBase;
  return {
    primaryBase,
    secondaryLagged,
    winner: secondaryWins ? "secondary" : "primary",
    value: secondaryWins ? secondaryLagged : primaryBase,
  };
}

/* -------------------------------------------- */
/* Skill-point pools (§2.2)                      */
/* -------------------------------------------- */

/** The six abilities that each generate an attribute-restricted skill-point pool. */
export const POOL_ABILITIES = /** @type {const} */ (["str", "dex", "con", "int", "wis", "cha"]);

/** Flat, always-generic skill points granted per level regardless of ability scores. */
export const FLAT_SKILL_POINTS_PER_LEVEL = 2;

/**
 * Points generated by one ability's pool: its modifier, floored at 0 (a
 * negative modifier contributes 0 points, never a deduction) — see
 * Docs/house-rules Open Question #7 (resolved).
 *
 * @param {pf1.documents.ActorPF} actor
 * @param {"str"|"dex"|"con"|"int"|"wis"|"cha"} abilityId
 */
export function abilityPoolPoints(actor, abilityId) {
  const mod = actor.system.abilities?.[abilityId]?.mod ?? 0;
  return Math.max(mod, 0);
}

/**
 * All 7 pools for a level of this actor: one per ability plus the flat
 * generic bonus. Only the "con" pool is unrestricted-by-default per §2.2.2
 * (spendable on any skill); the other five are restricted to skills
 * governed by that ability (with Intimidate special-cased to allow either
 * "str" or "cha" — see ui/skill-pool-panel.mjs, which is where that
 * restriction is actually enforced/displayed).
 *
 * @param {pf1.documents.ActorPF} actor
 * @returns {Record<string, number>}
 */
export function skillPointPools(actor) {
  const pools = {};
  for (const id of POOL_ABILITIES) pools[id] = abilityPoolPoints(actor, id);
  pools.flat = FLAT_SKILL_POINTS_PER_LEVEL;
  return pools;
}

/** Sum of all 7 pools — the total skill points granted this level. */
export function totalSkillPointsPerLevel(actor) {
  return Object.values(skillPointPools(actor)).reduce((sum, v) => sum + v, 0);
}

/**
 * Career-total unrestricted skill ranks granted by anything OTHER than the
 * six ability-pool formulas above: race features (e.g. Human Skilled:
 * `@attributes.hd.total`), feats, class features, or the sheet's manual
 * "Bonus Skill Rank Formula" field — anything that lands on the
 * `bonusSkillRanks` Change target / `system.details.bonusSkillRankFormula`.
 *
 * Scans every item on the actor (not just the race), since a feat or class
 * feature can grant `bonusSkillRanks` too — see Docs/house-rules §2.2: any
 * such bonus is unrestricted, so the skill pool panel folds all of it into
 * Generic rather than only the racial piece. This deliberately does NOT read
 * the already-computed `system.details.skills.bonus` total, because that
 * would also pick up `changes/skill-points-total.mjs`'s own reconciliation
 * Changes (already fully accounted for across the six ability pools) and
 * double-count them.
 *
 * Already counted by pf1 via each source's own `bonusSkillRanks` Change, so
 * this must not be added to {@link totalSkillPointsPerLevel} — that would
 * double-count.
 *
 * @param {pf1.documents.ActorPF} actor
 * @returns {number}
 */
export function otherBonusSkillRanks(actor) {
  const rollData = typeof actor.getRollData === "function" ? actor.getRollData() : {};
  let total = 0;
  for (const item of actor?.items ?? []) {
    for (const change of Object.values(item.system?.changes ?? {})) {
      if (change.target !== "bonusSkillRanks") continue;
      total += pf1.dice.RollPF.safeRollSync(String(change.formula ?? 0), rollData).total || 0;
    }
  }

  const manualFormula = actor?.system?.details?.bonusSkillRankFormula;
  if (manualFormula) {
    total += pf1.dice.RollPF.safeRollSync(String(manualFormula), rollData).total || 0;
  }

  return total;
}

/**
 * Career-total Favored Class Bonus points already banked into skills
 * (each eligible class's own `system.fc.skill.value`, set by whatever the
 * player picked at each level-up). pf1 adds this natively to the Skills
 * tab's `skillRanks.allowed` total (base-character-sheet.mjs `_prepareSkills`)
 * on top of the per-class base formula this module replaces — it is NOT
 * part of the six ability-pool formulas, but it IS unrestricted same as
 * the "con"/"flat" pools, so the skill-pool panel folds it into Generic
 * (see ui/skill-pool-panel.mjs) so the panel's total and the header's
 * `skillRanks.allowed` stay equal even when FCB-into-skills is in play.
 *
 * CORRECTION (verified live): RefCode's `base-character-sheet.mjs` checks
 * `pf1.config.favoredClassTypes.has(subType)` (a Set), but the installed
 * v11.11 build's actual `pf1.config.favoredClassTypes` is a plain Array
 * (`.includes`) — same family of RefCode-vs-shipped-build drift flagged
 * throughout this module. `includesFavoredClassType` below checks for
 * either shape so this keeps working if a future pf1 update switches back
 * to a Set.
 *
 * @param {pf1.documents.ActorPF} actor
 * @returns {number}
 */
export function favoredClassSkillBonus(actor) {
  let total = 0;
  for (const cls of actor?.itemTypes?.class ?? []) {
    if (!includesFavoredClassType(pf1.config.favoredClassTypes, cls.system.subType)) continue;
    total += cls.system.fc?.skill?.value || 0;
  }
  return total;
}

/**
 * @param {Set<string>|string[]|undefined} collection
 * @param {string} value
 */
function includesFavoredClassType(collection, value) {
  if (!collection) return false;
  return typeof collection.has === "function" ? collection.has(value) : collection.includes(value);
}

/**
 * pf1's own skill id for Intimidate is literally `"int"` — a different
 * namespace than (and easy to confuse with) the Intelligence ABILITY id
 * `"int"`. `pf1.config.skills.int.ability` is `"cha"` by default; this
 * constant exists so every reference to "the Intimidate skill id" in this
 * module goes through one clearly-labeled name instead of a bare `"int"`
 * that reads like the ability.
 */
export const INTIMIDATE_SKILL_ID = "int";

/**
 * Which skill-point pools a given skill's ranks may be paid from: its own
 * governing ability's pool, plus the always-unrestricted "con" and "flat"
 * pools — with Intimidate additionally allowed to draw from "str" per
 * Docs/house-rules §2.2 ("Intimidate may use either STR or CHA").
 *
 * @param {string} skillId
 * @returns {string[]} pool keys (a subset of [...POOL_ABILITIES, "flat"])
 */
export function skillGoverningPools(skillId) {
  const ability = pf1.config.skills?.[skillId]?.ability;
  const pools = new Set(["con", "flat"]);
  if (ability) pools.add(ability);
  if (skillId === INTIMIDATE_SKILL_ID) pools.add("str");
  return [...pools];
}
